Support Armv7
ARM-software/astc-encoder pull request #237
Opened 2021-03-10 11:42 UTC by rchardx

Support armv7 by adding armv7-compatible intrinsics.

* Compilation for Android: please refer to [armv7_compile.txt](https://github.com/ARM-software/astc-encoder/files/6115443/armv7_compile.txt).
  * Compiler:
> Android clang version 3.8.275480  (based on LLVM 3.8.275480)
> Target: x86_64-apple-darwin20.3.0
> Thread model: posix
> InstalledDir: /Users/.../Library/Android/sdk/ndk/14.1.3816874/toolchains/llvm/prebuilt/darwin-x86_64/bin/.
  * Option "-O3 -Wno-unused-command-line-argument" must be used for armv7.
* Unit Test: the results are shown in [unittest_armv7.txt](https://github.com/ARM-software/astc-encoder/files/6115456/unittest_armv7.txt)
  * Both aarch64 and armv7 fail vint4.two_to_the_n test.
  * Other fails are related to floating-point arithmetic.

2021-03-10 12:09 UTC, solidpixel requested changes
Thanks for the PR. Some code review comments added.

2021-03-10 12:09 UTC, solidpixel commented on Source/astcenc_vecmathlib_neon_armv7_4.h
> +	float32_t a0 = ::nearbyintf(vgetq_lane_f32(a, 0));
Prefer these to have an explicit `std::nearbyint`.

2021-03-10 12:09 UTC, solidpixel commented on Source/astcenc_vecmathlib_neon_armv7_4.h
> +	return {a0, a1, a2, a3};
Coding style nit - spaces between braces and fields please.

2021-03-10 12:09 UTC, solidpixel commented on Source/astcenc_vecmathlib_neon_armv7_4.h
> +ASTCENC_SIMD_INLINE uint32_t vaddvq_u32(uint32x4_t a)
Please remove vaddvq; it's no longer needed as I removed uses of it in the main aarch64 NEON code, and it's impossible to make invariant with x86 SIMD implementations.

2021-03-10 12:09 UTC, solidpixel commented on Source/astcenc_vecmathlib_neon_armv7_4.h
> +	a = vmaxq_f32(a, vdupq_n_f32((std::numeric_limits<float>::min)()));
Please replace with a scalarized version using `std::sqrt()`. Reciprocal sqrt is not invariant across implementations, and we have a strict invariance requirement.

2021-03-10 13:27 UTC, solidpixel commented
Note, I fixed the aarch64 NEON issue with the `vint4.two_to_the_n` unit test (invalid test - was shifting more than the data type could contain), so the unit tests should be clean.

2021-03-10 16:38 UTC, solidpixel reviewed
Do you have any build of this that works outside of a smartphone - e.g. for Arm Linux?

My main concern with accepting this as a PR is that I currently have no sensible way of testing it in our CI system. Our current aarch64 testing is on macOS, but I can't run 32-bit binaries there.

2021-03-11 08:27 UTC, rchardx commented
I have fixed compilation issues on arm linux, including an assert error in two_to_the_n.
Current changes are ready to be compiled if vaddvq were removed.

* Compilation for Android Armv7
  * Script: [android_armv7_compile.txt](https://github.com/ARM-software/astc-encoder/files/6121456/android_armv7_compile.txt)
  * All tests passed!
* Compilation for ARM-based linux using arm-linux-gnueabi-g++
  * Env: Ubuntu 20.04, arm-linux-gnueabi-g++9.3
  * Script: [ubuntu_armv7_compile.sh.txt](https://github.com/ARM-software/astc-encoder/files/6121458/ubuntu_armv7_compile.sh.txt)
  * Executable file: [test-simd-neon_ubuntu2004_arm-linux-gnueabi-g++9.3.zip](https://github.com/ARM-software/astc-encoder/files/6121469/test-simd-neon_ubuntu2004_arm-linux-gnueabi-g%2B%2B9.3.zip)
  * Sadly, I have no ARM32 linux devices and therefore did not run the tests.

2021-03-11 10:44 UTC, solidpixel commented
Thanks for the update. For running on Armv7 I've been using using `qemu-user` as an emulator. 

`
apt-get install qemu-user
export QEMU_LD_PREFIX=/usr/arm-linux-gnueabi
qemu-user ./astcenc/test-simd-neon
`

2021-03-11 10:51 UTC, solidpixel commented
Still one test fail in debug builds (my fault). Let me merge that to `main` with the vaddvq removal change.

2021-03-11 10:55 UTC, rchardx commented
> Thanks for the update. For running on Armv7 I've been using using `qemu-user` as an emulator on an x86-64 machine.
> 
> ```
> apt-get install qemu-user
> export QEMU_LD_PREFIX=/usr/arm-linux-gnueabi
> qemu-user ./astcenc/test-simd-neon
> ```

Armv7 on linux (release) passed all tests using qemu-arm.

2021-03-11 12:02 UTC, solidpixel approved these changes

2021-03-11 12:03 UTC, merged

2021-03-11 12:04 UTC, solidpixel commented
Merged; still some work to do Arm-side to add some test automation using `qemu-user`, but I'll handle that as a separate commit.

2023-09-19 12:31 UTC, Lyt-BUPT commented
why this support is delete in the new master?

2023-09-19 12:36 UTC, rchardx commented
> Why this support is delete in the new master? Is there any new replace way to get .a library that can be used on android armv7 devices?

astc-encoder dropped the support of armv7 devices.
You can just use older versions of the repo.

2023-09-19 12:42 UTC, solidpixel commented
The main problem is that it wasn't actually Armv7 complaint - it was really a hybrid of Armv7 and Armv8 AArch32. The main reason we removed it was that we had no way to test it, and increasingly 32-bit software is getting phased out so the cost of maintaining and adding testing for it doesn't make a huge amount of sense.

As above, old release tags are still live if needed.

2023-09-19 19:40 UTC, solidpixel commented
https://github.com/ARM-software/astc-encoder/tree/3.0 is the last release tag that still supported this.

2023-09-20 03:46 UTC, Lyt-BUPT commented
> > Why this support is delete in the new master? Is there any new replace way to get .a library that can be used on android armv7 devices?
> 
> astc-encoder dropped the support of armv7 devices. You can just use older versions of the repo.

I got it. Thanks for your replies!

2023-09-20 03:46 UTC, Lyt-BUPT commented
> https://github.com/ARM-software/astc-encoder/tree/3.0 is the last release tag that still supported this.


I got it. Thanks for your replies!