Add namespacing to CMake interface
ARM-software/astc-encoder pull request #409
Opened 2023-05-15 19:07 UTC by solidpixel

2023-05-16 09:19 UTC, wasimabbas-arm requested changes

2023-05-16 09:19 UTC, wasimabbas-arm commented on Source/UnitTest/cmake_core.cmake
> +add_test(ASTCENC_TARGET_NAME ${ASTCENC_TEST}
This is a mistake. "NAME" is keyword in "add_test" it shouldn't be renamed.

2023-05-16 09:19 UTC, wasimabbas-arm commented on Source/UnitTest/cmake_core.cmake
> +add_test(ASTCENC_TARGET_NAME ${ASTCENC_TEST}
Also how does the actual name shows up? looks like the "COMMAND" and "NAME" are the same.

2023-05-16 09:42 UTC, solidpixel commented on Source/CMakeLists.txt
> +    foreach(ASTCENC_INDEX RANGE ${ASTCENC_ARTIFACTS_LEN})
Let's not introduce more typing if we can avoid - will remove.

2023-05-17 09:37 UTC, wasimabbas-arm commented
Approved.

2023-05-17 09:49 UTC, merged